$schema: "1.0"
name: InstallChocoPackage
command: "./InstallChocoPackage.ps1 -Package {{package}} -Version {{version}} -IgnoreChecksums {{ignoreChecksums}}"
parameters:
  package:
    defaultValue: ""
    type: string
    required: true
  version:
    defaultValue: ""
    type: string
    required: false
  ignoreChecksums:
    defaultValue: false
    type: boolean
    required: false